#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit"
# To disable this hook, rename this file to "pre-commit.sample"

# Redirect output to stderr.
exec 1>&2

echo "PRE-COMMIT: TODO actually do tests here"
exit 0